function plot_histogram(filename)

    data = readmatrix(filename);
    apps = categorical({'apache', ...
            'leveldb', ...
            'memcached', ...
            'mysql', ...
            'nginx', ...
            'postgresql', ...
            'redis', ...
            'rocksdb'});

    benches = {'init', ...
        'crypto', ...
        'net', ...
        'drivers', ...
        'security', ...
        'virt', ...
        'certs', ...
        'arch', ...
        'lib', ...
        'mm', ...
        'ipc', ...
        'fs', ...
        'kernel', ...
        'block'};

    [~,idx] = sort(sum(data), 'descend');
    benches = benches(idx);
    data = data(:,idx);

    h = [0,30,60,120,180,240,300,150,210,270,330,15,45,90] / 360;
    s = linspace(1,1,14);
    v = linspace(1,1,14);
    cmap = squeeze(hsv2rgb(cat(3,h,s,v)));

    f = figure();
    b = bar(apps, data, 'stacked');
    for i = 1 : length(b)
        b(i).FaceColor = cmap(i,:);
    end

    legend(benches, 'location', 'eastoutside')
    %title('Line Frequency by Module Composition')
    xlabel('Application');
    ylabel('Composition');

    ax = gca();
    ax.FontSize=14;
    ax.YLim = [0,1];

    print(f, 'eecs582_line_module_hist', '-dpng')
end